runtime: python39

env_variables:
  FLASK_ENV: production
  SECRET_KEY: your-super-secret-key-change-this-in-production

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
